--  Configuration for functional_tests generated by Alire
pragma Restrictions (No_Elaboration_Code);
pragma Style_Checks (Off);

package Functional_Tests_Config is
   pragma Pure;

   Crate_Version : constant String := "3.0.0";
   Crate_Name : constant String := "functional_tests";

   Alire_Host_OS : constant String := "macos";

   Alire_Host_Arch : constant String := "x86_64";

   Alire_Host_Distro : constant String := "homebrew";

   type Build_Profile_Kind is (release, validation, development);
   Build_Profile : constant Build_Profile_Kind := development;

end Functional_Tests_Config;
